package:
  name: pyne
  version: "0.5.0rc1"

source:
  fn: pyne-src.tar.gz  # ["TRAVIS" not in environ]
  url: https://github.com/pyne/pyne/archive/master.tar.gz  # ["TRAVIS" not in environ]
  path: ..  # ["TRAVIS" in environ]

requirements:
  build:
    - python
    - gcc  # [osx]
    - cmake
    - cython
    - moab
    - lapack
    - pytables
    - hdf5
    - numpy
    - scipy
  run:
    - python
    - gcc  # [osx]
    - moab
    - pytaps # [py2k]
    - hdf5
    - lapack
    - numpy
    - scipy
    - pytables

test:
  requires:
    - nose
    - jinja2

about:
  home: http://pyne.io/
  license: BSD
